[project]
name = "ai-in-politics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "lxml>=6.0.2",
    "python-slugify>=8.0.4",
    "requests>=2.32.5",
    "tldextract>=5.3.0",
    "tqdm>=4.67.1",
    "trafilatura>=1.6.1",
]
